### ISSUE TITLE
Refactor Command Parsing Code

### ISSUE THREAD

**Issue by Koloss0** [UMSATS/soti#17]
The way commands are parsed is needlessly complex. Refactor the command parsers with a more convenient switch statement. The commands in `command_args.py` are also out of date with the new command reference.

**Comment by ArnavG-it** [comment]
Is [this](https://docs.google.com/spreadsheets/d/1fF_nCTbqJ7y3KoorSmB4DAGctDv61TSHfD0VK8CovCM/edit?gid=1728821240#gid=1728821240) the up-to-date command list? It doesn't list the command codes so I'm unsure how to determine which command is being received.

**Comment by Koloss0** [comment]
Yeah, that's the one. It doesn't have command codes cause they can easily change at any time. You should create an enum type that matches the [TUK command codes](https://github.com/UMSATS/tsat-utilities-kit/blob/main/Inc/tuk/can_wrapper/can_command_list.h).

That way in the future if we make any changes, we just have to modify those two files.

**Comment by Koloss0** [comment]
See #18

**Comment by ArnavG-it** [comment]
I see. I've done that and updated `COMM_INFO` so far [here](https://github.com/UMSATS/soti/blob/eb14d5c52ea8bf8dbd057c71460fc9ca6ddf8a80/soti-cli/cli_utils/constants.py), it's a bit awkward but abstracts away from command codes. The user would still have to provide the correct number when using the send command, but having the enum opens some options for improving the interface for that command in the future.

Also, should the command destinations just be the subsystems they belong to? There will have to be a small workaround for the commands without a destination because looking up `None` in `NodeID` will crash, but that should be straightforward.
